"""지표 레지스트리 — canonical 정의는 docs/specs/dashboard-mvp/requirements.md R1 참조."""

from sources import ecos, fdr_source, fred, naver, treasury, yfinance_source

INDICATORS = {
    "investor_kospi": dict(
        name="주체별 순매수 (코스피)",
        type="flows",
        unit="억원",
        columns=["individual", "foreign", "institution"],
        instrument="KRX 코스피 현물 거래대금 기준 개인/외국인/기관 일별 순매수",
        source_label="naver:investorDealTrendDay:sosok=01",
        module=naver,
        profile="afterclose",
    ),
    "investor_kosdaq": dict(
        name="주체별 순매수 (코스닥)",
        type="flows",
        unit="억원",
        columns=["individual", "foreign", "institution"],
        instrument="KRX 코스닥 현물 거래대금 기준 개인/외국인/기관 일별 순매수",
        source_label="naver:investorDealTrendDay:sosok=02",
        module=naver,
        profile="afterclose",
    ),
    "kospi": dict(
        name="코스피",
        type="ohlcv",
        unit="pt",
        instrument="KRX 산출 코스피 지수 종가",
        source_label="fdr:KS11",
        module=fdr_source,
        profile="afterclose",
    ),
    "kosdaq": dict(
        name="코스닥",
        type="ohlcv",
        unit="pt",
        instrument="KRX 산출 코스닥 지수 종가",
        source_label="fdr:KQ11",
        module=fdr_source,
        profile="afterclose",
    ),
    "samsung": dict(
        name="삼성전자",
        type="ohlcv",
        unit="원",
        instrument="삼성전자(005930) 일봉 OHLCV",
        source_label="fdr:005930",
        module=fdr_source,
        profile="afterclose",
    ),
    "skhynix": dict(
        name="SK하이닉스",
        type="ohlcv",
        unit="원",
        instrument="SK하이닉스(000660) 일봉 OHLCV",
        source_label="fdr:000660",
        module=fdr_source,
        profile="afterclose",
    ),
    "usdkrw": dict(
        name="원/달러",
        type="line",
        unit="KRW",
        instrument="USD/KRW 글로벌 FX 시장환율 일봉 종가",
        source_label="yfinance:KRW=X",
        module=yfinance_source,
        profile="preopen",
    ),
    "usdjpy": dict(
        name="달러/엔",
        type="line",
        unit="JPY",
        instrument="USD/JPY 글로벌 FX 시장환율 일봉 종가",
        source_label="yfinance:JPY=X",
        module=yfinance_source,
        profile="preopen",
    ),
    "wti": dict(
        name="WTI",
        type="line",
        unit="USD/bbl",
        instrument="NYMEX WTI 최근월 선물 종가",
        source_label="yfinance:CL=F",
        module=yfinance_source,
        profile="preopen",
    ),
    "ust10y": dict(
        name="미국채 10년",
        type="line",
        unit="%",
        instrument="미 재무부 Daily Par Yield Curve 10년물",
        source_label="treasury:10Yr",
        module=treasury,
        profile="preopen",
        fallback_module=fred,
        fallback_source_label="fred:DGS10",
    ),
    "ktb3y": dict(
        name="국고채 3년",
        type="line",
        unit="%",
        instrument="ECOS 국고채 3년 최종호가수익률",
        source_label="ecos:817Y002:010200000",
        module=ecos,
        profile="afterclose",
    ),
}

PROFILES = {
    "preopen": [k for k, v in INDICATORS.items() if v["profile"] == "preopen"],
    "afterclose": [k for k, v in INDICATORS.items() if v["profile"] == "afterclose"],
}
PROFILES["all"] = list(INDICATORS.keys())
